name: minigptv
channels:
  - nvidia
  - pytorch-nightly
  - conda-forge  
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - cuda-toolkit
  - huggingface_hub
  - matplotlib
  - psutil
  - iopath
  - pyyaml
  - regex
  - tokenizers
  - tqdm
  - transformers
  - timm
  - webdataset
  - omegaconf
  - opencv
  - peft
  - sentence-transformers
  - gradio
  - accelerate
  - bitsandbytes
  - scikit-image
  - visual-genome
  - wandb
  - pip
  - pip:
    - decord
    - visual-genome
