name: minigptv
channels:
  - nvidia
  - pytorch-nightly
  - conda-forge  
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cuda-toolkit=12.1
  - huggingface-hub
  - matplotlib
  - psutil
  - iopath
  - pyyaml
  - regex
  - tokenizers
  - tqdm
  - transformers
  - timm
  - webdataset
  - omegaconf
  - opencv-python
  - decord
  - peft
  - sentence-transformers
  - gradio
  - accelerate
  - bitsandbytes
  - scikit-image
  - visual-genome
  - wandb
